openapi: 3.0.0
info:
  version: 0.3.2
  title: WWI16AMA - Spec
  license:
    name: APL 2
servers:
  - url: 'http://wwi16ama.feste-ip.net/backend_api/'
paths:
  /members:
    $ref: 'https://raw.githubusercontent.com/will-code-for-food-and-water/api_spec/master/test.yaml#/~1members'
  '/members/{id}':
    $ref: 'https://raw.githubusercontent.com/will-code-for-food-and-water/api_spec/master/test.yaml#/~1members~1%7Bid%7D'
  /planes:
    get:
      summary: List of all planes
      operationId: listPlanes
      tags:
        - Planes
      parameters: 
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
            default: 20
        - name: start
          in: query
          description: How many items to skip
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: orderBy
          in: query
          description: The field by which the result is to be sorted
          required: false
          schema:
            type: string
            default: name
        - name: direction
          in: query
          description: the sorting direction
          required: false
          schema:
            type: string
            enum: ["asc", "desc"]
            default: "asc"
      responses:
        '200':
          description: A paged array of planes
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Plane'
        '400':
          description: This error is thrown when the parameters are faulty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a Plane
      operationId: createPlanes
      requestBody:
        description: Plane to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPlane'
      tags:
        - Planes
      responses:
        '200':
          description: Responds with the Plane and all his fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plane'
        '400':
          description: Response when request is wrong, i.e. if required fields are empty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/planes/{id}':
    get:
      summary: Info for a specific Plane
      operationId: showPlaneById
      tags:
        - Planes
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Plane to retrieve
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plane'
        '404':
          description: Response when no Plane found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a specific Plane
      operationId: updatePlaneById
      tags:
        - Planes
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Plane to update
          schema:
            type: integer
            format: int32
      requestBody:
        description: Plane to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPlane'
      responses:
        '204':
          description: Expected response to a valid request
        '400':
          description: Response when request is wrong, i.e. if required fields are empty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Response when no Plane found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete specific plane
      operationId: deletePlaneById
      tags:
        - Planes
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Plane to delete
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Expected response to a valid request
        '404':
          description: Response when no Plane found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /fees:
    get:
      summary: List of fees
      tags:
        - Fees
      responses:
        '200':
          description: An array of fees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fee'
  /accounts:
    get:
      summary: Paginated list of accounts without transactions.
      tags:
        - Accounts
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
            default: 20
        - name: start
          in: query
          description: How many items to skip
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: orderBy
          in: query
          description: The field by which the result is to be sorted
          required: false
          schema:
            type: string
            default: lastName
        - name: direction
          in: query
          description: the sorting direction
          required: false
          schema:
            type: string
            enum: ["asc", "desc"]
            default: "asc"
      responses:
        '200':
          description: A paged array of Accounts
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/ListAccount'
        '400':
          description: This error is thrown when the parameters are faulty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/accounts/{id}':
    get:
      summary: Info for a specific Account with his Transactions
      tags:
        - Accounts
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Member to retrieve
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Response when no Account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/accounts/{id}/transactions':
    post:
      summary: Add Transactions to an Account
      tags:
        - Accounts / Transactions
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the related Account
          schema:
            type: integer
            format: int32
      requestBody:
        description: Transactions to add to the Account
        required: true
        content:
          application/json:
            schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewTransaction'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Response when request is wrong, i.e. if required fields are empty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Response when no Member found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Member:
      $ref: 'https://raw.githubusercontent.com/will-code-for-food-and-water/api_spec/master/test.yaml#/components/schemas/Member'
    NewMember:
      $ref: 'https://raw.githubusercontent.com/will-code-for-food-and-water/api_spec/master/test.yaml#/components/schemas/NewMember'
    ListMember:
      $ref: 'https://raw.githubusercontent.com/will-code-for-food-and-water/api_spec/master/test.yaml#/components/schemas/ListMember'
    Address:
      $ref: 'https://raw.githubusercontent.com/will-code-for-food-and-water/api_spec/master/test.yaml#/components/schemas/Address'
    Error:
      required:
        - url
        - message
      properties:
        url:
          type: string
        message:
          type: string
    NewPlane:
      required:
        - number
        - name
        - position
        - neededAuthorization
      properties:
        number:
          type: string
        name:
          type: string
        position:
          type: string
        neededAuthorization:
          type: string
          enum: [PPLA, PPLB]
    Plane:
      allOf:
        - required:
          - id
          properties:
            id:
              type: integer
              format: int32
        - $ref: '#/components/schemas/NewPlane'
    Fee:
      required:
        - category
        - fee
      properties:
        category:
          type: string
          enum: [ACTIVE, U20ACTIVE, PASSIVE, HONORARYMEMBER]
        fee:
          type: integer
          format: int32
    ListAccount:
      properties:
        id:
          type: integer
          format: int32
        balance:
          type: number
          format: double
    Account:
        allOf:
        - properties:
            transactions:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
        - $ref: '#/components/schemas/ListAccount'
    NewTransaction:
      required:
        - amount
        - type
      properties:
        amount:
          type: number  
          format: double
        type:
          type: string
          enum: ["GEBÜHR", "AUFWANDSENTSCHÄDIGUNG", "ZAHLUNG"]
    Transaction:
      allOf:
        - properties:
            id:
              type: integer
              format: int64
            timestamp:
              type: string
              format: date-time
        - $ref: '#/components/schemas/NewTransaction'
